#This is a guessing game
guess_number() {
   #We declare a random number and assign it to a variable called rand_number
   rand_number=$((RANDOM % $1))
   #There we use the for loop, through the game
   for i in {0..2}; do
      guest_number = $2
      #If the random number generated by the computer and that inputted by the user is thesame
      if [ $rand_number -eq $2 ]; then
         echo "YOU WON!"
         break
      elif [ $rand_number -gt $2 ]; then
         echo "YOU MISSED! The random number is greater than $2"
         read -p "Please try again: " guest_number
         $2 = $guest_number
      else
         echo "YOU MISSED! The random number is less than $guest_number"
         read -p "Please try again: " guest_number
         $2 = $guest_number
      fi
   done
   if [ i -eq 3 ]; then
   echo "YOU LOSE! The random number was $rand_number"
   fi
}
